name: touchable_opacity
description: This widget lets you provide a more visual feedback to users when they interact with your app, similar to TouchableOpacity in React Native.
version: 1.1.1
repository: https://github.com/nkshah2/touchable_opacity
issue_tracker: https://github.com/nkshah2/touchable_opacity/issues
documentation:
homepage: https://github.com/nkshah2/touchable_opacity

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

