name: touchable_opacity
description: >-
  This widget lets you provide a more visual feedback to users when they interact with your app. When the user touches the widget,
  the opacity of the widget changes informing the user that their action has not been ignored.
version: 1.0.0
author: Nemi Shah <nemishah1212@gmail.com>
repository: https://github.com/nkshah2/touchable_opacity
issue_tracker: https://github.com/nkshah2/touchable_opacity/issues
documentation:
homepage: https://github.com/nkshah2/touchable_opacity

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

